#!/usr/bin/env ruby

require "rbgithook"
require "fileutils"

command = ARGV[0]

if %w[add set].include?(command)
  args = ARGV[1..]
  Rbgithook.send(command, args)
else
  begin
    Rbgithook.send(command)
  rescue NoMethodError => _
    puts "Unknown command: #{command}\n\n"

    Rbgithook.help
  end
end
