#!/usr/bin/env ruby

require "rbgithook"
require "fileutils"

command = ARGV[0]

cmds = {
  "install" => ->(_) { Rbgithook.install },
  "set" => ->(args) { Rbgithook.set(args) },
  "add" => ->(args) { Rbgithook.add(args) },
  "uninstall" => ->(_) { Rbgithook.uninstall },
  "help" => ->(_) { Rbgithook.help }
}

cmds.key?(command) ? cmds[command].call(ARGV[1..]) : Rbgithook.help
