#!/usr/bin/env ruby

require "rbgithook"

command = ARGV.shift

unless command
  warn "Please specify a command to run\n\n"
  Rbgithook.help
  exit 1
end

cmds = {
  "install" => ->(_) { Rbgithook.install },
  "set" => ->(args) { Rbgithook.set(args) },
  "add" => ->(args) { Rbgithook.add(args) },
  "list" => ->(_) { Rbgithook.list },
  "uninstall" => ->(_) { Rbgithook.uninstall },
  "help" => ->(_) { Rbgithook.help }
}

cmds[command] ? cmds[command].call(ARGV) : Rbgithook.help
