name: Ruby

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['2.7.0','3.0.0','3.1.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Test the module
      run: bundle exec rspec
